"""Tests for the Memory TypedDict."""

import datetime
import importlib.util
import uuid
from pathlib import Path
from typing import Any, NotRequired, get_args, get_origin, get_type_hints

from src.agent.state import Memory

# Load database_types from the supabase/ project directory (not the supabase pip package).
_spec = importlib.util.spec_from_file_location(
    "database_types",
    Path(__file__).resolve().parents[2] / "supabase" / "database_types.py",
)
assert _spec
assert _spec.loader
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
PublicMemories = _mod.PublicMemories


# Mapping from PublicMemories field types to their expected Memory equivalents.
_DB_TO_MEMORY_TYPE: dict[type | object, type | object] = {
    uuid.UUID: uuid.UUID,
    datetime.datetime: datetime.datetime,
    datetime.datetime | None: datetime.datetime | None,
    str | None: str | None,
    Any | None: dict[str, Any],
    int: int,
    float: float,
    str: str,
}


def test_memory_fields_match_public_memories_schema() -> None:
    """Verify Memory TypedDict stays in sync with the autogenerated PublicMemories model.

    If a field exists in both types, their type annotations must be compatible.
    This test will fail when the DB schema changes, prompting an update to Memory.
    """
    memory_hints = get_type_hints(Memory, include_extras=True)
    db_fields = PublicMemories.model_fields

    memory_only = {"similarity"}
    db_only = {"embedding"}

    shared_fields = set(db_fields.keys()) & set(memory_hints.keys()) - memory_only - db_only

    assert shared_fields, "No shared fields found — check for renames in the DB schema"

    db_hints = get_type_hints(PublicMemories, globalns=vars(_mod))

    for field_name in sorted(shared_fields):
        db_annotation = db_hints[field_name]
        mem_annotation = memory_hints[field_name]

        if get_origin(mem_annotation) is NotRequired:
            mem_annotation = get_args(mem_annotation)[0]

        expected = _DB_TO_MEMORY_TYPE.get(db_annotation)
        assert expected is not None, (
            f"Field '{field_name}': unmapped DB type {db_annotation!r} — "
            f"add it to _DB_TO_MEMORY_TYPE"
        )
        assert mem_annotation == expected, (
            f"Field '{field_name}' type mismatch: "
            f"Memory has {mem_annotation!r} but DB schema implies {expected!r}"
        )
